name: Lint
on: push
jobs:
  backend:
    name: "Lint backend"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install
      working-directory: api

    - name: Run ESLint
      run: cd api && npm run lint:check
  
  frontend:
    name: "Lint frontend"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install

    - name: Run ESLint
      run: npm run lint:check